EXPERIMENT:
  NAME: ""
  TAG: "mlkd_dkd,res110,M-res32"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "MLKD_DKD"
  TEACHER: "resnet110"
  STUDENT: "res110_M_r32"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  BETA: 2.0
