EXPERIMENT:
  NAME: "NO_3_BRANCH,vgg16,res44"
  TAG: "mlkd_dkd,vgg16,M-res44"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "MLKD_DKD"
  TEACHER: "vgg16"
  STUDENT: "vgg16_M_r44"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  BETA: 2.0
